name: CI

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Repository 접근
        uses: actions/checkout@v4

      - name: JDK 21 셋팅
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 셋팅
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: '8.7'

      - name: 프로젝트 빌드
        run: |
          ./gradlew build
          ./gradlew generateDependencyGraph
